- hbook/yodacnv/yoda.go
- hbook/yodacnv/yoda_test.go
This CL adds a new package yodacnv to help with reading and writing YODA
files.
Fixes go-hep/hep#17
> hbook/yodacnv: add Read/Write convenience functions

- hbook/rootcnv/root.go
- hbook/rootcnv/root_test.go
- rootio/cmd/root-srv/server/data.go
- rootio/cmd/root-srv/server/plots.go
- rootio/cmd/root-srv/server/server.go
This CL adds a new function `rootcnv.S2D` to convert `rootio.Graph` or `rootio.GraphErrors` values into `hbook.S2D` ones.
> Rootio cnv graph

- fastjet/algorithm_test.go
- fastjet/clustersequence.go
Solves #65 & #63 
I tried to model the exclusive jets after the c++ version
> Implement ExclusiveJets & EeKtAlgorithm 

- hbook/h2d.go
> hbook: adding accessor to h2d binning

- fastjet/internal/predicates/bigfunctions.go
- fastjet/internal/predicates/doc.go
- fastjet/internal/predicates/float64Pred.go
- fastjet/internal/predicates/incircle.go
- fastjet/internal/predicates/incircle_test.go
- fastjet/internal/predicates/orientation.go
- fastjet/internal/predicates/orientation_test.go
> predicates: implement predicates

- fastjet/internal/delaunay/delaunay.go
- fastjet/internal/delaunay/doc.go
- fastjet/internal/delaunay/point.go
- fastjet/internal/delaunay/point_test.go
- fastjet/internal/delaunay/triangle.go
- fastjet/internal/delaunay/triangle_test.go
This PR has the data structures and the frame work for the delaunay implementation
> fastjet/internal/delaunay: new package to implement delaunay triangulation

- joss-paper/paper.md
> joss-paper: Contact for Bastian Wieck

- joss-paper/paper.md
> joss-paper: Contact for David Blyth

- fastjet/clustersequence.go
PR to start the implementation of jet clustering using the Delaunay triangulation.
> fastjet: jet clustering using delaunay first stab

- fastjet/internal/delaunay/delaunay.go
- fastjet/internal/delaunay/delaunay_test.go
This PR handles duplicate points. When a duplicate point is inserted it only updates the nearest neighbor of itself and the duplicate point. When it is removed nothing happens.
> fastjet/internal/delaunay: handle duplicate points

- README.md
- joss-paper/paper.bib
- joss-paper/paper.md
> joss-paper: first stab

- geo/gdml/gdml.go
- geo/gdml/gdml_test.go
This CL adds the fundations for a GDML library.
Updates go-hep/hep#138.
> geo/gdml: first import

- xrootd/cmd/xrootd-client/main.go
- xrootd/cmd/xrootd-srv/main.go
- xrootd/xrootd.go
- xrootd/xrootd_test.go
This CL just creates the basic package layout for xrootd.
> xrootd: first import

- xrootd/mux/mux.go
- xrootd/mux/mux_test.go
Add mux package which manages channels by their ids.
Is part of #170, #179 and is built on top of #183.
I'm still not sure how to make several PRs and keep them "stacked". I'm sorry if I messed it up.
> xrootd: add mux

- xrootd/client/client.go
It is set to false when the channel is already closed.
> xrootd/client: fix 'more' usage in channel reading

- xrootd/internal/mux/mux.go
- xrootd/internal/mux/mux_test.go
So all active request calls will unblock and receive an error message stating that Close was called.
> xrootd/internal/mux: close all channels with error message after Close

- xrootd/client/filesystem_test.go
I've messed up with the request to the server and it recreated a test file.
> xrootd: fix dirlist test

- xrootd/client/file.go
- xrootd/client/file_mock_test.go
- xrootd/xrdfs/file.go
- xrootd/xrdproto/sync/sync.go
> xrootd: add sync request

- xrootd/client/file.go
- xrootd/client/file_mock_test.go
- xrootd/client/file_test.go
- xrootd/xrdfs/file.go
- xrootd/xrdproto/signing.go
- xrootd/xrdproto/write/write.go
> xrootd: add write request

- xrootd/client/file.go
- xrootd/client/file_mock_test.go
- xrootd/client/file_test.go
- xrootd/client/filesystem.go
- xrootd/client/filesystem_mock_test.go
- xrootd/client/filesystem_test.go
- xrootd/xrdfs/file.go
- xrootd/xrdfs/fs.go
- xrootd/xrdproto/signing.go
- xrootd/xrdproto/truncate/truncate.go
> xrootd: add truncate request

- xrootd/client/filesystem.go
- xrootd/client/filesystem_mock_test.go
- xrootd/xrdfs/fs.go
- xrootd/xrdproto/mkdir/mkdir.go
- xrootd/xrdproto/signing.go
Server tests will be added together with the rmdir request.
Btw, specification is probably wrong regarding option: https://github.com/xrootd/xrootd/issues/736.
> xrootd: add mkdir request

- xrootd/client/file_test.go
- xrootd/client/filesystem.go
- xrootd/client/filesystem_mock_test.go
- xrootd/client/filesystem_test.go
- xrootd/xrdfs/fs.go
- xrootd/xrdproto/rmdir/rmdir.go
- xrootd/xrdproto/signing.go
> xrootd: add rmdir request

- xrootd/client/filesystem.go
- xrootd/client/filesystem_mock_test.go
- xrootd/client/filesystem_test.go
- xrootd/xrdfs/fs.go
- xrootd/xrdproto/mv/mv.go
- xrootd/xrdproto/signing.go
> xrootd: add mv request

- xrootd/client/filesystem.go
- xrootd/client/filesystem_mock_test.go
- xrootd/client/filesystem_test.go
- xrootd/xrdfs/fs.go
- xrootd/xrdproto/chmod/chmod.go
- xrootd/xrdproto/signing.go
> xrootd: add chmod request

- xrootd/client/file.go
- xrootd/client/file_mock_test.go
- xrootd/client/file_test.go
- xrootd/client/filesystem.go
- xrootd/client/filesystem_mock_test.go
- xrootd/client/filesystem_test.go
- xrootd/xrdfs/file.go
- xrootd/xrdfs/fs.go
- xrootd/xrdproto/chmod/chmod.go
- xrootd/xrdproto/signing.go
- xrootd/xrdproto/verifyw/verifyw.go
Note that tests indicate that this request is not supported by the XRootD server: https://github.com/xrootd/xrootd/issues/738
> xrootd: add verifyw request

- xrootd/client/file.go
- xrootd/client/file_mock_test.go
- xrootd/client/file_test.go
- xrootd/client/filesystem.go
- xrootd/client/filesystem_mock_test.go
- xrootd/client/filesystem_test.go
- xrootd/xrdfs/file.go
- xrootd/xrdfs/fs.go
- xrootd/xrdfs/stat.go
- xrootd/xrdproto/chmod/chmod.go
- xrootd/xrdproto/signing.go
- xrootd/xrdproto/statx/statx.go
- xrootd/xrdproto/verifyw/verifyw.go
> xrootd: add statx request

- xrootd/client/client.go
- xrootd/xrdproto/auth/auth.go
- xrootd/xrdproto/chmod/chmod.go
- xrootd/xrdproto/dirlist/dirlist.go
- xrootd/xrdproto/login/login.go
- xrootd/xrdproto/marshaling.go
- xrootd/xrdproto/mkdir/mkdir.go
- xrootd/xrdproto/mv/mv.go
- xrootd/xrdproto/open/open.go
- xrootd/xrdproto/ping/ping.go
- xrootd/xrdproto/protocol.go
- xrootd/xrdproto/protocol/protocol.go
- xrootd/xrdproto/read/read.go
- xrootd/xrdproto/rm/rm.go
- xrootd/xrdproto/rmdir/rmdir.go
- xrootd/xrdproto/signing.go
- xrootd/xrdproto/sigver/sigver.go
- xrootd/xrdproto/stat/stat.go
- xrootd/xrdproto/statx/statx.go
- xrootd/xrdproto/sync/sync.go
- xrootd/xrdproto/truncate/truncate.go
- xrootd/xrdproto/verifyw/verifyw.go
- xrootd/xrdproto/write/write.go
- xrootd/xrdproto/xrdclose/xrdclose.go
I have tested it against the XRootD server with `compatible`, `standard`, `intense`, and `pedantic` levels.
> xrootd: add signing

- rootio/fileplugin.go
- xrootd/cmd/xrd-cp/main.go
- xrootd/xrdio/xrdio.go
This CL adds a new command xrd-cp to copy files and directories from a
remote xrootd to local storage.
Updates go-hep/hep#256.
> xrootd/cmd/xrd-cp: first import

- rootio/wbuffer.go
- rootio/wbuffer_test.go
> Rootio wbuffer opt

- README.md
- fads/energy_smearing.go
- fads/momentum_smearing.go
- fit/curve1d_test.go
- fwk/app.go
- hbook/ntup/ntuple_test.go
- hplot/h1d.go
- lhef/reader.go
- pawgo/cmd.go
- rootio/cmd/root-diff/main.go
- rootio/cmd/root-srv/server/plots.go
- rootio/read_streamers.go
- sio/stream.go
- xrootd/client/file_test.go
- xrootd/client/filesystem_test.go
- xrootd/cmd/xrootd-fuse/main.go
- xrootd/xrdproto/dirlist/dirlist.go
Fixes https://github.com/go-hep/hep/issues/284
> Goreport fixes

- fit/curve1d.go
- fit/hist.go
Fixes #290.
Updates gonum/gonum#538.
> fit: use new optimize Local-less API

- fit/curve1d.go
- fit/hist.go
> fit: update for new gonum/optimize.Minimize API

- xrootd/cmd/xrd-srv/handler.go
- xrootd/cmd/xrd-srv/main_test.go
- xrootd/server/default_handler.go
- xrootd/server/handler.go
- xrootd/server/server.go
> xrootd/server: add open, read, and close support

- xrootd/cmd/xrd-srv/handler.go
- xrootd/cmd/xrd-srv/main_test.go
- xrootd/server/default_handler.go
- xrootd/server/handler.go
- xrootd/server/server.go
- xrootd/xrdfs/stat.go
> xrootd/server: add write, stat, truncate, sync, rename requests

- rootio/wbuffer.go
> rootio: enable fast-path for WBuffer.Write-arrays

- rootio/cmd/root-cp/main.go
- rootio/cmd/root-cp/main_test.go
- rootio/dir.go
> rootio/cmd/root-cp: first import

- rootio/cmd/root-ls/testdata/dirs-6.14.00.root.txt
- rootio/dir.go
- rootio/file.go
- rootio/key.go
- rootio/objarray.go
- rootio/wbuffer_test.go
> rootio,rootio/cmd/root-ls: refactor tdirectory/tdirectoryFile

- xrootd/xrdproto/query/query.go
- xrootd/xrdproto/query/query_test.go
> xrootd/xrdproto/query: implement kXR_query request

- xrootd/xrdproto/prepare/prepare.go
- xrootd/xrdproto/prepare/prepare_test.go
- xrootd/xrdproto/query/query.go
> xrootd/xrdproto/prepare: implement kXR_prepare request

- xrootd/xrdproto/endsess/endsess.go
- xrootd/xrdproto/endsess/endsess_test.go
> xrootd/xrdproto/endsess: implement kXR_endsess

- xrootd/xrdproto/locate/locate.go
- xrootd/xrdproto/locate/locate_test.go
> xrootd/xrdproto/locate: implement kXR_locate

- xrootd/xrdproto/decrypt/decrypt.go
- xrootd/xrdproto/decrypt/decrypt_test.go
> xrootd/xrdproto/decrypt: implement kXR_decrypt

- xrootd/xrdproto/admin/admin.go
- xrootd/xrdproto/admin/admin_test.go
- xrootd/xrdproto/decrypt/decrypt.go
- xrootd/xrdproto/decrypt/decrypt_test.go
> xrootd/xrdproto/admin: implement kXR_admin

- xrootd/client/auth.go
- xrootd/client/client.go
- xrootd/xrdproto/auth/host/host.go
- xrootd/xrdproto/auth/host/host_test.go
- xrootd/xrdproto/auth/krb5/krb5.go
> xrootd/{client,xrdproto/auth/host}: implement "host" security provider

- groot/cmd/root-srv/main.go
- groot/cmd/root-srv/server/data.go
- groot/cmd/root-srv/server/plots.go
- groot/cmd/root-srv/server/server.go
- groot/example_test.go
- groot/rbytes/rbuffer.go
- groot/riofs/dir.go
- groot/riofs/file.go
- groot/riofs/file_test.go
- groot/riofs/walk.go
- groot/riofs/walk_example_test.go
- groot/riofs/walk_test.go
> groot/cmd/root-srv: open xrootd-served files when in local mode

- .travis.yml
- ci/run-tests.go
- groot/cmd/root-srv/page.go
- groot/rsrv/endpoints.go
also add a spinner.
Fixes #403.
> groot/cmd/root-srv: prevent double-clicks on plot requests

- groot/cmd/root-srv/data.go
- groot/cmd/root-srv/page.go
- groot/cmd/root-srv/server.go
- groot/rsrv/endpoints.go
> groot/{rsrv,cmd/root-srv}: implement a plot-request pipeline + per-request spinner

- groot/riofs/dir.go
- groot/riofs/dir_example_test.go
- groot/riofs/dir_test.go
- groot/riofs/file.go
- groot/riofs/key.go
- groot/riofs/riofs.go
- groot/riofs/walk.go
> groot/riofs: implement Directory.Mkdir

- groot/cmd/root-cp/main.go
- groot/cmd/root-diff/main.go
- groot/cmd/root-dump/main.go
- groot/cmd/root-ls/main.go
- groot/cmd/root-print/main.go
- groot/cmd/root-srv/plugins.go
- groot/example_test.go
- groot/riofs/dir_test.go
- groot/riofs/fileplugin.go
- groot/riofs/fileplugin_test.go
- groot/riofs/plugin/http/http.go
- groot/riofs/plugin/http/http_test.go
- groot/riofs/plugin/xrootd/xrootd.go
- groot/rsrv/rsrv_test.go
- groot/rtree/scanner_test.go
- groot/rtree/tchain_test.go
- groot/rtree/tree_test.go
> groot: introduce ROOT open plugin mechanism

- groot/rdict/gen.go
This CL removes the init-based code used to locate a few packages
(encoding, rbytes, ...) that are needed during code generation.
This required to have a Go installation and the source code of groot
whenever a binary importing groot or groot/rdict was launched.
Delay this code to be executed during the creation of an
rdict.Generator.
> groot/rdict: remove init-based code

- hbook/ntup/ntup_example_test.go
This CL adds example to
* Use scan function which manipulates input before plotting.
* Use H1D function which plots 1D histogram.
Signed off by Jay Batra <jaybatra73@gmail.com>
> hbook/ntup: add an examples of scan and H1D function.

- groot/rtree/basket.go
- groot/rtree/branch.go
- groot/rtree/leaf.go
- groot/rtree/rw_test.go
- groot/rtree/writer_example_test.go
> groot/rtree: add support var-len arrays to trees

- go.mod
- go.sum
- groot/rarrow/rarrow.go
- groot/rtree/basket.go
- groot/rtree/branch.go
- groot/rtree/rw_test.go
> groot/rtree: handle auto-flush

- cmd/arrow2root/main.go
- cmd/arrow2root/main_test.go
- cmd/arrow2root/testdata/lists.file.data.txt
- go.mod
- go.sum
- groot/rarrow/tree_writer.go
- reuse arrow/arrio.Copy scaffolding
- support writing slices
> cmd/arrow2root,groot/rarrow: introduce rarrow.NewFlatTreeWriter

- groot/cmd/root-merge/main.go
- groot/cmd/root-merge/main_test.go
- groot/rhist/graph.go
- groot/rhist/graph_example_test.go
- groot/rhist/graph_test.go
- groot/root/root.go
- groot/rtree/writer.go
- groot/rtree/writer_test.go
> groot/cmd/root-merge: first import

- cmd/root2fits/main.go
- cmd/root2fits/main_test.go
> cmd/root2fits: first import

- .travis.yml
- go.mod
- go.sum
- groot/rarrow/table.go
Apache/Arrow fixed the `check-ptr` issue with apache/arrow#6600.
Fixes #520.
> ci: re-instate full race test

- hplot/hplot.go
- hplot/latex.go
- hplot/latex_test.go
- hplot/options.go
> hplot: add ability to automatically generate PDFs from .tex

- hplot/hplot.go
- hplot/htex/latex.go
- hplot/htex/latex_test.go
Refactor LaTeX handling (auto-compilation via pdflatex) into its one
package: hplot/htex.
> hplot/htex: first import

- groot/rtree/example_reader_test.go
- groot/rtree/reader.go
- groot/rtree/reader_test.go
> groot/rtree: add ReadVarsFromStruct

- go.mod
- go.sum
- groot/rtree/example_reader_test.go
- groot/rtree/formula.go
- groot/rtree/formula_test.go
- groot/rtree/reader.go
> groot/rtree: implement a Formula interpreter

- groot/rtree/formula.go
- groot/rtree/formula_test.go
- groot/rtree/reader.go
> groot/rtree: add autoloading of branches for Formulae

- go.mod
- go.sum
- hplot/htex/example_handler_test.go
- hplot/htex/handler.go
- hplot/htex/handler_test.go
- hplot/htex/latex.go
GoHandler is an asynchronous latex compilation handler.
> hplot/htex: introduce GoHandler

- sliceop/f64s/example_f64s_test.go
- sliceop/f64s/f64s.go
I have implemented the three functions discussed in #650 with some tentatively clear comment for the doc. I don't know if we need to add examples for it.
> First version of the f64s package

- go.sum
- hbook/ann.go
- hbook/ann_test.go
- hbook/bin1d.go
- hbook/binning1d.go
- hbook/dist.go
- hbook/h1d.go
- hbook/h1d_test.go
- hbook/hbook.go
- hbook/hbook_test.go
- hbook/ops.go
- hbook/ops_test.go
> hbook: correctly handle add/sub

- groot/gen.rhist.go
- groot/rcmd/merge.go
- groot/rcmd/merge_test.go
- groot/rhist/h1_gen.go
Fixes go-hep/hep#549.
Updates go-hep/hep#547.
> groot/{rhist,rcmd}: implement root.Merger for rhist.H1x

- sliceop/f64s/example_f64s_test.go
- sliceop/f64s/f64s.go
> Adding Take() function

- groot/rsql/rsqldrv/driver.go
- groot/rsql/rsqldrv/expr.go
- groot/rsql/rsqldrv/rsqldrv_example_test.go
- groot/rsql/rsqldrv/types.go
> groot/rsql/rsqldrv: migrate to new database/sql/driver.XyzContext interfaces

- csvutil/csvdriver/driver.go
- csvutil/csvdriver/driver_test.go
- csvutil/csvdriver/import.go
> csvutil/csvdriver: implement new database/sql/driver.XyzContext

- groot/rtree/formula_test.go
> groot/rtree: add formula test for slices

- xrootd/client.go
- xrootd/client_test.go
- xrootd/session.go
- xrootd/session_mock_test.go
- xrootd/xrdio/xrdio.go
- xrootd/xrdio/xrdio_test.go
> xrootd{,/xrdio}: do not segfault closing nil clients or nil files

- xrootd/client.go
> xrootd: do not segfault sending data with nil clients

- groot/rtree/example_reader_test.go
- groot/rtree/reader.go
> groot/rtree: introduce Reader.Reset

- hplot/binerrband.go
- hplot/h1d.go
- hplot/hstack.go
Fixes https://github.com/go-hep/hep/issues/788
> Handling negative bin content and LogY

- groot/riofs/dir.go
- groot/riofs/file.go
- groot/riofs/key.go
- groot/riofs/rw_test.go
> groot/riofs: add support for writing big files

- groot/rtree/rw_test.go
> groot/rtree: test c-var-len-arrays

- groot/rdict/streamer.go
- groot/rdict/streamer_test.go
- groot/rtree/rw_test.go
> groot/{rdict,rtree}: handle groot types mirroring TObject inheritance tree

- groot/riofs/key.go
TKeys sizes computation was broken for "big files".
The code was indeed changing the `key.rvers` field to indicate
the "big file" mode was enabled, but it wasn't updating the
on-disk size of the TKey (ie: missing 8bytes).
This CL computes the correct size in one-go instead of fixing it
after the facts.
Fixes go-hep/hep#821.
> groot/riofs: fix overlaping blocks w/ big-file mode

- fmom/ops.go
- fmom/ops_test.go
Addressing https://github.com/go-hep/hep/issues/831
> Implementing VecOf(p4) function

- README.md
> doc: add link to forum discussion

- .github/workflows/ci.yml
- appveyor.yml
- go.mod
> all: bump to Go-1.16

- go.mod
- go.sum
> hep: bump klauspost/compress@v1.11.8

- .github/workflows/ci.yml
- .travis.yml
> ci: add support for Ubuntu-20 and headless X11 mode

- hplot/plot.go
- hplot/plot_test.go
> hplot: fix race in hplot.New on gonum/plot.DefaultFont

- go.mod
- go.sum
> all: bump klauspost/compress@v1.14.2

- cmd/npy2root/main.go
- cmd/npy2root/main_test.go
- cmd/root2npy/main.go
- groot/rnpy/arrow.go
- groot/rnpy/arrow_test.go
- groot/rnpy/column.go
- groot/rnpy/column_test.go
- groot/rnpy/rnpy.go
> groot/rnpy: new package to ease ROOT-Tree/NumPy conversion

- .github/workflows/ci.yml
> ci: use codecov-action@v2

- cmd/lhef2hepmc/main.go
> cmd/lhef2hepmc: improve warning message and display event number

- groot/doc.go
> groot: document interop model with ROOT/C++

- go.mod
- go.sum
> all: bump yaml@v3.0.1

- .github/workflows/ci.yml
> ci: bump actions/{setup-go,cache,checkout}@v3

- groot/rcmd/merge.go
- groot/riofs/walk.go
- groot/riofs/walk_test.go
> groot/riofs: provide a stable top-dir to Walk

- groot/riofs/file.go
- groot/riofs/key.go
- groot/rtree/writer_test.go
> groot/{riofs,rtree}: de-duplicate automatically generated This-streamers

- groot/internal/genroot/genroot_test.go
> all: 2023 is the year of the Gopher

- cmd/lhef2hepmc/main.go
> cmd/lhef2hepmc: add -keep-all flag to keep intermediaries

- hplot/io.go
- hplot/plot.go
- hplot/tiledplot.go
- hplot/vgop/canvas.go
- hplot/vgop/fonts.go
- hplot/vgop/json.go
- hplot/vgop/ops.go
- hplot/vgop/testdata/plot_golden.json
- hplot/vgop/testdata/simple_golden.json
- hplot/vgop/vgop.go
- hplot/vgop/vgop_test.go
Fixes https://github.com/go-hep/hep/issues/986.
> hplot/vgop: first import
