- README.md
- fads/btagging.go
- fads/calo.go
- fads/efficiency.go
- fads/energy_smearing.go
- fads/momentum_smearing.go
- fads/tautagging.go
- fastjet/algorithm_test.go
- fastjet/clustersequence_area_test.go
- fit/curve1d.go
- fit/curve1d_test.go
- fit/fit.go
- fit/hist.go
- fit/hist_test.go
- fit/run.go
- hbook/README.md
- hbook/h1d_test.go
- hbook/h2d_test.go
- hbook/p1d_test.go
- hbook/rootcnv/testdata/gen-2d-data.go
- hplot/README.md
- hplot/h1d_test.go
- hplot/h2d_test.go
- hplot/hplot_test.go
- hplot/s2d_test.go
- hplot/ticks.go
- hplot/tiledplot_test.go
Migrate to `gonum.org/v1/gonum/...` where possible (*ie:* drop `gonum/plot` from the migration for the moment)
> all: migrate to gonum.org/v1/gonum

- fastjet/internal/predicates/incircle.go
- fastjet/internal/predicates/incircle_test.go
- fastjet/internal/predicates/orientation.go
- fastjet/internal/predicates/orientation_test.go
This PR changes the close case predicates testing over to using the mat package. It also changes the mat functions up, to do the factorization in place.
> fastjet/internal/predicates: change over to mat

- fastjet/internal/delaunay/delaunay.go
- fastjet/internal/delaunay/delaunay_test.go
- fastjet/internal/delaunay/point.go
- fastjet/internal/delaunay/triangle.go
This PR implements the insertion using the hierarchical delaunay algorithm. 
The benchmark numbers are significantly worse than the version in the first PR without the predicates. The cpu profile shows that swapDelaunay takes up most of the time. That is where the incircle function is called. If possible improving the incircle function would be the best for the performance.
> fastjet/internal/delaunay: implement hierarchical delaunay insertion

- fastjet/internal/heap/doc.go
- fastjet/internal/heap/heap.go
- fastjet/internal/heap/heap_test.go
This PR implements a min heap that will be used in the delaunay clustering.
> fastjet/internal/heap: implement a min heap for pairs of jets

- fastjet/jet.go
> fastjet:  protect against parton-level events where pt can be zero for some partons, giving rapidity=infinity

- fastjet/internal/delaunay/delaunay.go
- fastjet/internal/delaunay/point.go
- fastjet/internal/delaunay/point_test.go
Added a function to remove the root points from the updatedNearestNeighbor slice from Insert and Remove.
Set the ID incrementally and added a function to access the ID, so that a jet can be mapped from a point.
> fastjet/internal/delaunay: remove root points from updated & set ID incrementally

- fastjet/internal/delaunay/point.go
- fastjet/internal/delaunay/point_test.go
Add the function SecondNearestNeighbor to handle when a jet's nearest neighbor is its own mirror point.  
Mirror points can be identified in runNlnN, but then the nearest neighbor that is not the mirror points needs to be found. That is when SecondNearestNeighbor comes to use.
> fastjet/internal/delaunay: add function SecondNearestNeighbor

- rootio/doc.go
The package doc was still refering to the old way to retrieve values
from a rootio.Directory.
Fix that and expand it a bit.
Updates go-hep/hep#112.
> rootio: update package doc, reference rootio examples

- cmd/root2npy/main.go
- hbook/rootcnv/root_test.go
- rootio/cmd/root-gen-datareader/main.go
- rootio/cmd/root-srv/server/plots.go
- rootio/dir.go
- rootio/doc.go
- rootio/file.go
- rootio/file_test.go
- rootio/graph_test.go
- rootio/key.go
- rootio/rootio.go
- rootio/scanner_example_test.go
- rootio/scanner_test.go
- rootio/tree_test.go
This CL modifies:
`Directory.Get(namecycle string) (Object, bool)`
to:
`Directory.Get(namecycle string) (Object, error)`
this allows to capture the context at the call site and thus reduces
code duplication when handling the error.
> all, rootio: make Directory.Get return an error instead of a boolean

- fastjet/internal/delaunay/delaunay.go
- fastjet/internal/delaunay/delaunay_test.go
- fastjet/internal/delaunay/point.go
- fastjet/internal/delaunay/point_test.go
- fastjet/internal/delaunay/triangle.go
- fastjet/internal/delaunay/triangle_test.go
This PR adds several functions to compute the Voronoi Diagram.
To handle the issue #111 I initially started implementing it where Voronoi points on the outside connect to its neighbor. But then after thinking about it more, I changed it to connect to the Circumcenter of the adjacent root triangle, which is just a dummy triangle. Those points are moved to the first and last position in the slice so that they are easy to identify. They might be useful to get a direction of where the line goes towards.
> fastjet/internal/delaunay: implement voronoi

- cmd/rio2yoda/main.go
- cmd/root2yoda/main.go
- cmd/yoda2rio/main.go
This CL adds support for gzipped YODA files.
If the input or output YODA file name ends with ".gz", the appropriate
gzip.Reader or gzip.Writer is inserted in the stack of readers or
writers.
> cmd/{rio,root}2yoda, cmd/yoda2rio: handle gzipped YODA files

- hbook/yodacnv/yoda.go
- hbook/yodacnv/yoda_test.go
This CL makes yodacnv.Read more lenient with unimplemented YODA types
(such as COUNTER, SCATTER1D, SCATTER3D and PROFILE2D.)
Fixes go-hep/hep#118.
> hbook/yodacnv: make Read more lenient wrt unimplemented YODA types

- rootio/cmd/root-diff/main.go
- rootio/cmd/root-print/main.go
This CL adds a WIP command to print (to PNG, PDF, ...) histograms from
ROOT files.
Its CLI is loosely based on `rootprint` from ROOT-6.
```
Usage: root-print [options] file.root [file.root [...]]
ex:
$> root-print -f pdf ./testdata/histos.root
$> root-print -f pdf ./testdata/histos.root:h1
$> root-print -f pdf ./testdata/histos.root:h*
$> root-print -f pdf -o output ./testdata/histos.root:h1
options:
-f string
output format for plots (pdf, png, svg, ...) (default "pdf")
-o string
output directory for plots
-v	enable verbose mode
```
> rootio/cmd/root-print: first import

- hbook/rootcnv/root.go
- hbook/rootcnv/root_test.go
- rootio/cmd/root-print/main.go
- rootio/cmd/root-srv/server/plots.go
- rootio/gen-code.go
- rootio/h1_gen.go
- rootio/h2_gen.go
- rootio/rootio.go
This CL introduces 2 new interfaces:
- rootio.H1
- rootio.H2
They describe 1-dim and 2-dim ROOT histograms.
Note that a rootio.H2 is not a rootio.H1.
> rootio, hbook/rootcnv: introduce H1 and H2 interfaces

- rootio/file.go
- rootio/fileplugin.go
- rootio/fileplugin_test.go
- rootio/tree_test.go
This CL implements a naive remote ROOT file handling over HTTP(S).
rootio.Open will seamlessly download the whole ROOT file into a
temporary local file.
This local file will be automatically removed when closed.
Updates go-hep/hep#142.
> rootio: implement naive remote ROOT file over HTTP

- rootio/compress.go
- rootio/key.go
TKeys with large payloads are split into multiple 16*1024*1024 bytes
chunks.
This CL adds support for this case.
> rootio: handle large TKey blobs

- rootio/tchain_test.go
Hello, 
There are many errors in the next proposition, but the idea is to add an argument to the loadEntry method : totalEntries. totalEntries is the total number of entries of the chain. This, i think, will allow to increase the nevbuf (number of entries in the basket) in order to be able to scan a chain containing more than one tree. Is it a way according to you ? 
Thanks
> Rootio tchain scanner

- xrootd/encoder/encoder.go
- xrootd/mux/mux.go
Do not add package docs to the encoder and protocol since they will be
merged to the single package (so, just postpone it to that moment).
Fixes https://github.com/go-hep/hep/issues/192.
> xrootd: fix docs

- rootio/cmd/root-srv/server/server.go
Drop satori/go.uuid in favor of pborman/uuid.
> rootio/cmd/root-srv/server: migrate to pborman/uuid

- xrootd/client/client.go
- xrootd/client/client_test.go
- xrootd/client/cxx_server_test.go
- xrootd/client/handshake.go
- xrootd/protocol/handshake/handshake.go
- xrootd/protocol/protocol.go
- xrootd/protocol/streamID.go
Add client package which allows to send requests and receive responses from XRootD server.
Add handshake request which performs an initial handshake.
Benchmark result is 150 ms/op which equals 2 * ping to the XRootD server.
Is part of https://github.com/go-hep/hep/issues/170.
I have extracted the client-related part from https://github.com/go-hep/hep/pull/179 to make it easier to review core component.
Specific requests will come as separated PR if it's ok and makes the review process easier. :)
> xrootd/client: first import

- xrootd/client/client.go
- xrootd/internal/mux/mux.go
- xrootd/internal/mux/mux_test.go
> xrootd/internal/mux: migrate from xrootd/mux

- xrootd/client/client.go
- xrootd/client/main_mock_test.go
- xrootd/client/protocol.go
- xrootd/client/protocol_mock_test.go
- xrootd/client/protocol_test.go
- xrootd/protocol/handshake/handshake.go
- xrootd/protocol/protocol.go
- xrootd/protocol/protocol/protocol.go
- xrootd/protocol/signing.go
Add Protocol request which queries for such info as:
- Protocol version
- Server type
- Security version
- Security options
- Security level
- Security overrides, that customize predefined security level
Information about security level and security overrides will further be used for signing requests when it's required by the server.
Client clean-up in the mock test is a bit awful due to not decided (yet) way of closing.
Response parsing is a bit awful too, since it copies data twice - from slice to the structs and then assembles these structs in more complicated response.
I want to make a generator of `Marshal`\\`Unmarshal` functions and handle bit-wise encoding and support of nested structs, slice length and so on.
Something like: 
```go
type ProtocolInfo struct {
BinaryProtocolVersion …
```
> xrootd/{client,protocol}: add protocol request

- xrootd/client/protocol_mock_test.go
Fix a random test failure introduced in #195.
If cancel() is called before client handled request, then the client
will raise an error indicating that (expected behaviour if we called
Close while some requests were blocked).
In case of test failure, it's safe to call cancel()
before the end of request handling because of the fact that
the actual error message will still be present at top of the log.
> xrootd/client: fix test

- xrootd/internal/mux/mux.go
In one of the previous PRs, it was decided that channels will be unbuffered since making them buffered doesn't make much sense. However accidentally in `ClaimWithID ` channel remained to be buffered, this PR fixes that.
> xrootd/internal/mux: make channels unbuffered in both Claim{,WithID}

- rootio/scanner.go
- rootio/tchain.go
- rootio/tchain_test.go
This CL implements the needed modifications to baseScanner to support
scanning a Chain via NewTreeScanner.
Missing support (code+tests):
- NewTreeScannerVars
- NewScannerVars
- NewScanner
Updates go-hep/hep#44.
> rootio: implement scanner for Chain

- xrootd/client/client.go
- xrootd/client/handshake.go
- xrootd/client/login.go
- xrootd/client/login_mock_test.go
- xrootd/client/main_mock_test.go
- xrootd/client/protocol.go
- xrootd/client/protocol_mock_test.go
- xrootd/client/protocol_test.go
- xrootd/internal/mux/mux.go
- xrootd/internal/mux/mux_test.go
- xrootd/xrdproto/gen-marshal.go
- xrootd/xrdproto/handshake/handshake.go
- xrootd/xrdproto/login/login.go
- xrootd/xrdproto/marshaling.go
- xrootd/xrdproto/marshaling_test.go
- xrootd/xrdproto/protocol.go
- xrootd/xrdproto/protocol/protocol.go
- xrootd/xrdproto/signing.go
mechanically produced with:
```
mkdir pkg
gomvpkg -from go-hep.org/x/hep/xrootd/protocol/login -to go-hep.org/x/hep/xrootd/pkg/login -vcs_mv_cmd "git mv {{.Src}} {{.Dst}}"
gomvpkg -from go-hep.org/x/hep/xrootd/protocol/handshake -to go-hep.org/x/hep/xrootd/pkg/handshake -vcs_mv_cmd "git mv {{.Src}} {{.Dst}}"
gomvpkg -from go-hep.org/x/hep/xrootd/protocol/protocol -to go-hep.org/x/hep/xrootd/pkg/protocol -vcs_mv_cmd "git mv {{.Src}} {{.Dst}}"
gomvpkg -from go-hep.org/x/hep/xrootd/protocol -to go-hep.org/x/hep/xrootd/xrdproto -vcs_mv_cmd "git mv {{.Src}} {{.Dst}}"
gomvpkg -from go-hep.org/x/hep/xrootd/pkg/protocol -to go-hep.org/x/hep/xrootd/xrdproto/protocol -vcs_mv_cmd "git mv {{.Src}} {{.Dst}}"
gomvpkg -from go-hep.org/x/hep/xrootd/pkg/handshake -to …
```
> xrootd/...: rename package protocol into xrdproto

- xrootd/client/filesystem.go
- xrootd/client/filesystem_mock_test.go
- xrootd/client/filesystem_test.go
- xrootd/xrdfs/fs.go
- xrootd/xrdfs/stat.go
- xrootd/xrdproto/dirlist/dirlist.go
- xrootd/xrdproto/signing.go
I'm not sure about testing via `fs.Dirlist(context.Background(), "/tmp/.xrootd")`, since response may change. Probably we need to create some permanent directory on the remote server for test purposes?
> xrootd: add dirlist request

- xrootd/client/file.go
- xrootd/client/filesystem.go
- xrootd/client/filesystem_mock_test.go
- xrootd/client/filesystem_test.go
- xrootd/xrdfs/file.go
- xrootd/xrdfs/fs.go
- xrootd/xrdproto/open/open.go
- xrootd/xrdproto/signing.go
Updates go-hep/hep#170 (haven't included in the commit message since I expect rebases because of https://github.com/go-hep/hep/pull/214 and https://github.com/go-hep/hep/pull/211 and it will pollute issue with each commit)
Note that `open` request isn't added to `signing.go` because it creates a cycle import. Any suggestions on how to deal with that? Probably we can move `signing` to `protocol/signing` to fix that?
Also, note that there is a test workaround due to https://github.com/xrootd/xrootd/issues/721.
Also, I'm unsure about `UnmarshalXrd` in `EntryStat` and `NewEntryStat`. It duplicates logic, but otherwise  call to `UnmarshalXrd` in `dirlist.go`, `(Response) UnmarshalXrd(...)` will be like that:
```go
o.Entries[i/2].UnmarshalXrd(xrdenc.NewRBuffer([]byte(lines[i+1)]))
```
> xrootd: add open request

- xrootd/client/file.go
- xrootd/client/file_mock_test.go
- xrootd/client/file_test.go
- xrootd/client/filesystem_mock_test.go
- xrootd/client/filesystem_test.go
- xrootd/xrdfs/file.go
- xrootd/xrdproto/signing.go
- xrootd/xrdproto/xrdclose/xrdclose.go
Note that `TestFile_CloseVerify` test is skipped.
From the [specs, p. 41](http://xrootd.org/doc/dev45/XRdv310.pdf):
>fsize the size, in bytes, that the file is to have. The close operation fails and the
file is erased if it is not of the indicated size. An fsize of zero suppresses the
check
As far as I understand, `close operation fails` means that response will contain the error, however, the response is `ok` when I provide wrong `fsize`.
I'm going to fill an issue to clarify this behavior. :)
> xrootd: add close request

- xrootd/client/file.go
- xrootd/client/file_mock_test.go
- xrootd/client/file_test.go
- xrootd/xrdfs/file.go
- xrootd/xrdproto/read/read.go
- xrootd/xrdproto/signing.go
I would like to implement [io.ReaderAt](https://golang.org/pkg/io/#ReaderAt) (and probably `io.Reader`) interface but I'm not sure about naming of methods that take a `context` as a parameter.
And basically it will be like:
```go
func (f file) ReadAt(p []byte, off int64) (n int, err error) {
return f.ReadAtWithContext(context.Background(), p, off)
}
```
What do you think? Should we implement such methods? Any suggestions about naming?
> xrootd: add read request (without read-ahead usage)

- xrootd/client/file.go
- xrootd/client/file_mock_test.go
- xrootd/client/file_test.go
- xrootd/xrdfs/file.go
- xrootd/xrdproto/read/read.go
- xrootd/xrdproto/signing.go
- xrootd/xrdproto/write/write.go
This CL modifies the read.Response unmarshaler to use the provided
buffer if it's big enough.
Otherwise, a new big enough buffer is allocated.
> xrootd/{client,xrdproto/read}: make ReadAt directly use provided buffer

- xrootd/client/file.go
- xrootd/client/file_mock_test.go
- xrootd/client/file_test.go
- xrootd/client/filesystem.go
- xrootd/client/filesystem_mock_test.go
- xrootd/client/filesystem_test.go
- xrootd/xrdfs/file.go
- xrootd/xrdfs/fs.go
- xrootd/xrdfs/stat.go
- xrootd/xrdproto/signing.go
- xrootd/xrdproto/stat/stat.go
Note that TestFile_FetchVirtualStatInfo is failing with an error: `xrootd: error 3001: Required argument not present`. I think that it's because it is called with `handle` instead of `path` (`FileSystem` calls it with `path` and it works correctly),
Can you take a look at [specs for kXR_stat](http://xrootd.org/doc/dev45/XRdv310.htm#_Toc464248850), please?
Especially:
>Notes
>...
>4)      kXR_stat - kXR_vfs requests need not specify an existing filesystem object. The specified path is used as a path prefix in order to filter out servers and partitions that could not be used to hold objects whose path starts with the specified path prefix.
I think that since there is no mention of `handle` it's not obvious that `kXR_stat` *requires* `path` to be passed and doesn't work when only `handle` is …
> xrootd: add stat request

- rootio/fileplugin.go
- xrootd/xrdfs/file.go
This CL adds:
- an `os.File.Name`-like method to `xrdfs.File`
- the according implementation for `xrootd/client.file`
- proper computation of the `rootio.xrdFile` size, using `kXR_stat`.
> Rootio xrd stat support

- xrootd/client/filesystem_test.go
Use ranges instead of exact values to prevent failing due to changes in files.
> xrootd: fix virtual stat test

- xrootd/xrdproto/handshake/handshake.go
The XRootD specs define the handshake as a 20-bytes payload, sliced as 5
int32s.
Instead of modeling this with a struct with 5 "reserved" fields, define
the request as a [5]int32 type.
> xrootd/xrdproto/handshake: replace request struct with array

- xrootd/client/auth.go
- xrootd/client/client.go
- xrootd/client/lookupgid_unix.go
- xrootd/client/lookupgid_windows.go
- xrootd/xrdproto/auth/auth.go
- xrootd/xrdproto/signing.go
Updates go-hep/hep#250.
I have tested it locally against the XRootD server with such config:
```
ofs.trace all
xrd.trace all
#sec.level all pedantic force
xrootd.seclib /usr/lib/libXrdSec.so
sec.protocol /usr/lib/ unix
sec.protocol /usr/lib/ pwd
sec.protbind * unix pwd
acc.authdb /tmp/Authfile
ofs.authorize 1
```
/tmp/Authfile is:
```
u ematirov /tmp a
u DESKTOP-R8CLF5C\ematirov /tmp a
```
Note that even Windows is supported by **unix** auth. :-P
> xrootd: add auth request together with unix auth

- xrootd/client/auth.go
- xrootd/client/client.go
- xrootd/xrdproto/auth/auth.go
- xrootd/xrdproto/auth/krb5/krb5.go
- xrootd/xrdproto/auth/krb5/krb5_unix.go
- xrootd/xrdproto/auth/krb5/krb5_windows.go
- xrootd/xrdproto/auth/unix/lookupgid_unix.go
- xrootd/xrdproto/auth/unix/lookupgid_windows.go
- xrootd/xrdproto/auth/unix/unix.go
@sbinet, could you please give this a try?
I have managed to install and configure Kerberos and that PR works locally with my config. However, yours may differ and it would be cool to test that before polishing it. :)
For the tests, edit the `xrootd/client/auth.go:26` and following lines. That enables Kerberos auth with the provided parameters to all usages of the client, so you can test it against `xrd-cp` for example. :)
I think that we'll receive in the `Client` configured and logged-in client to the Kerberos, so it will allow a user to fully customize the creation of the client.
Another possibility is to introduce `xrootd/auth/krb5` and depend on `gokrb5` only from that package, requiring only basic interface from the `Client` side. Something like:
```go
type KerberosAuth interface { …
```
> xrootd: add krb5 auth

- xrootd/xrdproto/chmod/chmod.go
- xrootd/xrdproto/dirlist/dirlist.go
- xrootd/xrdproto/mkdir/mkdir.go
- xrootd/xrdproto/mv/mv.go
- xrootd/xrdproto/open/open.go
- xrootd/xrdproto/protocol.go
- xrootd/xrdproto/rm/rm.go
- xrootd/xrdproto/rmdir/rmdir.go
- xrootd/xrdproto/stat/stat.go
- xrootd/xrdproto/truncate/truncate.go
This allows any request with a file path to have correct `opaque` after redirection.
> xrootd: implement FilepathRequest interface in corresponding requests

- xrootd/cmd/xrootd-fuse/main.go
- xrootd/xrdfuse/cxx_server_test.go
- xrootd/xrdfuse/file.go
- xrootd/xrdfuse/xrdfuse.go
- xrootd/xrdfuse/xrdfuse_test.go
- xrootd/xrdproto/protocol.go
Supports:
- ls
- echo "..." > file
- echo "..." >> file
- cat file
Note: probably I should move error codes to the xrdproto package?
Updates go-hep/hep#174.
Updates go-hep/hep#175.
> xrootd/{cmd/xrootd-fuse,xrdfuse}: first import

- fads/energy_smearing.go
- fads/momentum_smearing.go
- fwk/app.go
- hbook/ntup/ntuple_test.go
- hplot/h1d.go
- lhef/reader.go
- pawgo/cmd.go
- rootio/cmd/root-diff/main.go
- rootio/cmd/root-srv/server/plots.go
- rootio/read_streamers.go
- sio/stream.go
- xrootd/client/file_test.go
- xrootd/client/filesystem_test.go
- xrootd/cmd/xrd-client/main.go
- xrootd/cmd/xrd-fuse/main.go
- xrootd/cmd/xrd-srv/main.go
- xrootd/cmd/xrootd-fuse/main.go
- xrootd/xrdproto/dirlist/dirlist.go
For consistency with the other go-hep/xrootd commands, rename
xrootd-fuse as xrd-fuse.
> xrootd/cmd/xrd-fuse: rename from xrootd-fuse

- xrootd/client/file_mock_test.go
- xrootd/client/filesystem_mock_test.go
- xrootd/client/filesystem_test.go
- xrootd/client/login_mock_test.go
- xrootd/client/main_mock_test.go
- xrootd/client/ping_mock_test.go
- xrootd/client/ping_test.go
- xrootd/client/protocol_mock_test.go
- xrootd/client/session.go
- xrootd/client/session_mock_test.go
- xrootd/cmd/xrd-srv/handler.go
- xrootd/cmd/xrd-srv/main_test.go
- xrootd/server/default_handler.go
- xrootd/server/server.go
- xrootd/server/server_test.go
- xrootd/xrdfuse/xrdfuse.go
- xrootd/xrdproto/protocol.go
- xrootd/xrdproto/protocol_test.go
Cleanup tests and main code by extracting `SendResponse`, `ReadResponse`, and `ReadRequest` functions.
Add for the sake of perfomance and avoiding extra allocations `ReadResponseWithReuse` that takes `headerBytes` slice and pointer to `header` as arguments.
Extract helper methods from session.consume for the better readability.
Rename `*Code` constants in `protocol.go`
> xrootd: cleanup

- rootio/fileplugin.go
- rootio/fileplugin_test.go
We cannot delete file that is currently opened.
Closes go-hep/hep#334.
> rootio: fix tmpFile behaviour under Windows

- rootio/cmd/root-ls/main.go
- printout was corrupted with trees in directories
- printout did write `TKey` for all classes for me
I was testing with /afs/cern.ch/user/p/pseyfert/public/sbinet/DTT.root (file
currently readable for @sbinet, I didn't check if I can publish the file and
didn't yet cook up an example for which could be used for testing).
Without fixing I got as printout:
```
peyfert@robusta ~/coding/go > go run src/github.com/go-hep/hep/rootio/cmd/root-ls/main.go -t /afs/cern.ch/user/p/pseyfert/DTT.root
=== [/afs/cern.ch/user/p/pseyfert/DTT.root] ===
version: 60205
TKey    EventTuple EventTuple (cycle=1)
TKey  TKey    B02DD   B02DD   (cycle=1)
TKey  TKey    GetIntegratedLuminosity GetIntegratedLuminosity (cycle=1)
TKey  % …
```
> hotfixes for root-ls -t

- cmd/yoda2rio/main.go
- cmd/yoda2root/main.go
- cmd/yoda2root/main_test.go
This CL adds a simple command that converts YODA files into ROOT files.
Fixes go-hep/hep#350.
> cmd/yoda2root: first import

- ci/run-tests.go
- hbook/dist.go
- hbook/dist_brio.go
- hbook/h1d.go
- hbook/h2d.go
- hbook/p1d.go
- rootio/compress.go
- rootio/compress_test.go
- rootio/consts.go
- rootio/gen-code.go
- rootio/h1_gen.go
- rootio/h2_gen.go
- rootio/key.go
- rootio/key_test.go
- rootio/objstring.go
Key.Type() allows to infer a key's payload's type w/o having to actually
unmarshal the whole object from disk.
> rootio: introduce Key.Type to infer key's payload's type

- go.mod
- go.sum
- xrootd/xrdproto/auth/krb5/krb5.go
This CL leverages gokrb5.v6 to properly handle unsupported directive
errors that stem from e.g. krb5.conf sections like:
```
[realms]
CERN.CH  = {
default_domain = cern.ch
kpasswd_server = cerndc.cern.ch
admin_server = cerndc.cern.ch
kdc = cerndc.cern.ch
v4_name_convert = {
host = {
rcmd = host
}
}
}
```
the v4 parts are not supported by gokrb5.
this used to be fatal (in the sense that xrootd couldn't generate a
proper authentication token) but didn't need to be.
now, gokrb5.v6 returns this new config.UnsupportedDirective error that
we recognize and "handle" (by ignoring it.)
Fixes go-hep/hep#355.
>  xrootd/xrdproto/auth/krb5: handle unsupported directive parsing errors

- rootio/attfill.go
- rootio/attline.go
- rootio/attmarker.go
- rootio/factory_test.go
- rootio/file.go
- rootio/file_example_test.go
- rootio/hist.go
- rootio/streamers.go
This CL introduces and hardcodes default streamers.
This is temporary, until we correctly manage (possibly deep) inheritance
hierarchies.
Updates #370.
> rootio: introduce default streamers

- groot/cmd/root-srv/data.go
- groot/rtree/branch.go
This CL makes sure we don't clobber previously read baskets' buffers.
Previously, we were trying to be clever and re-use a per-branch buffer
for reading baskets' contents.
This worked correctly when crawling through data once.
But when going through events twice, the data part of the buffer for
event, e.g., 10, could contain random data from previously read event
190001.
Fixes #390.
> groot: dont clobber basket buffer

- xrootd/cmd/xrd-ls/main.go
Fixes output format of xrd-ls. 
Previously, directory name was omitted which resulted in ` \tmp\x\y\a.txt` being shown as `\tmp\x\a.txt`.
> xrootd/cmd/xrd-ls: fix output format

- xrootd/fshandler.go
According to http://xrootd.org/doc/dev45/XRdv310.pdf, p. 100:
If more data is requested than the file contains, the total of all
dlen’s will be less than rlen (in other words, response length will be
less that requested length).
> xrootd: fix Read fshandler

- groot/rbase/attline.go
- groot/rcolors/colors.go
- groot/rhist/axis.go
- groot/rhist/hist.go
So a H1D created with groot can be correctly displayed by ROOT.
> groot: add sensible defaults for AttLine, Axis and H1

- hbook/ntup/ntup_example_test.go
This CL adds example to create histogram from a
CSV.
Fixes go-hep/hep#186.
Signed off by: Jay Batra <jaybatra73@gmail.com>
> hbook/ntup: add example on how to create histos from CSV

- .travis.yml
Apache Arrow has some issues with the new unsafe-pointer arithmetic
analysis pass of the next Go-1.14.
see:
https://issues.apache.org/jira/browse/ARROW-7029
> ci: temporarily disable ASM when in race mode for Go-1.14

- groot/rtree/rw_test.go
- groot/rtree/writer.go
- groot/rtree/writer_example_test.go
This allows to reliably defer Writer.Close()
> groot/rtree: make tree.writer close idempotent

- cmd/lhef2hepmc/main.go
- fads/fastjet_finder.go
- fads/utils.go
- fmom/eetaphim.go
- fmom/etetaphim.go
- fmom/iptcotthphim.go
- fmom/ops.go
- fmom/p4.go
- fmom/ptetaphim.go
- fmom/pxpypze.go
- hepmc/decoder.go
- hepmc/hepmc.go
- hepmc/hepmc_test.go
this is for performance reasons, see:
- golang/go#15925
> all: introduce fmom.Vec4, make fmom.PxPyPzE a struct instead of [4]float64

- groot/rtree/formula_test.go
- groot/rtree/scanner.go
> groot/rtree: allow Reader with 0-len rvars slice

- hbook/h1d.go
- hbook/h1d_test.go
I am not sure this can be done respecting the logic of the code, given this comment for `h.Value()`
>  Value implements `gonum/plot/plotter.Valuer`
But if it is possible, here is the (super simple) function.
Fixes go-hep/hep#656.
> Adding h.Error() function

- hbook/h1d.go
- hbook/h1d_test.go
Starting to implement Add() function, for now without uncertainty propagation. I would need to *set* the `bin.sumW2()`, which I am not sure how to do with only `bin.fill(x, w)` approach.
Fixes go-hep/hep#652.
> Implementation of Add() and Divide() function for hbook.H1D

- fads/cmd/fads-rivet-mc-generic/mcalg.go
- hbook/ops.go
- hbook/ops_test.go
Following https://github.com/go-hep/hep/issues/659, and ooking at https://github.com/go-hep/hep/blob/a50ee1ad8cc2d7923eec6c476508f67758d52379/hbook/ops.go#L35                                               
I think we could just implement this way, *i.e.* explicitly ask to ignore NaN points. This could be done simply by                                    
```go
func DivideH1D(num, den *H1D, ignoreNaN bool) (*S2D, error) {
for i := range bins1 { 
// ... 
switch {                                                                                                                                        
case b2h == 0 || (b1h == 0 && b1herr != 0): // TODO(sbinet): is it OK?                
y = math.NaN()
ey = math.NaN() 
if ignoreNane {
continue
}
//...
}
//...
s2d.Fill(Point2D{X: x, Y: y, ErrX: …
```
> Option to discard NaNs in hbook.DivideH1D()

- sliceop/f64s/f64s.go
- sliceop/f64s/f64s_test.go
Reduce memory allocation:
- from populating the map and
- from using sort.IntsAreSorted.
also removed a loop over indices by removing sort.IntsAreSorted.
```
name                old time/op    new time/op    delta
Take/Len=2-4          63.5ns ± 3%     6.1ns ± 1%   -90.45%  (p=0.000 n=18+18)
Take/Len=4-4          82.7ns ± 2%     6.9ns ± 2%   -91.64%  (p=0.000 n=19+20)
Take/Len=8-4           116ns ± 2%       8ns ± 2%   -93.33%  (p=0.000 n=18+20)
Take/Len=128-4        4.03µs ± 1%    0.07µs ± 2%   -98.24%  (p=0.000 n=20+19)
Take/Len=1024-4       31.8µs ± 1%     0.5µs ± 3%   -98.44%  (p=0.000 n=17+19)
Take/Len=1048576-4    57.2ms ± 2%     3.1ms ± 4%   -94.61%  (p=0.000 n=19+20)
name                old alloc/op   new alloc/op   delta
Take/Len=2-4           32.0B ± 0%      0.0B       -100.00% …
```
> sliceop/f64s: improve performances of Take

- hplot/s2d.go
Fixes https://github.com/go-hep/hep/issues/684
I propose to change names of these field, so that they match the ones of `H1D`.
> Exporting XErrs and YErrs

- go.mod
- go.sum
this CL uses a hopefully temporary fork of gomacro that doesn't import
testing/quick.
> hep: use gomacro from go-hep

- groot/gen.rtree.go
- groot/rbytes/rbuffer.go
- groot/rbytes/rw_test.go
- groot/rtree/basket.go
- groot/rtree/branch.go
- groot/rtree/leaf_gen.go
- groot/rtree/rtree.go
- groot/rtree/rw_test.go
- groot/rtree/scanner.go
a set of various optimisations that bring:
```
$> benchstat ref.txt new.txt
name                      old time/op    new time/op    delta
ReadTreeF64-4                483µs ± 3%     437µs ± 5%   -9.58%  (p=0.000 n=19+20)
ReadTreeSliF64/0-4           213µs ± 2%     154µs ± 2%  -27.57%  (p=0.000 n=20+19)
ReadTreeSliF64/1-4           213µs ± 1%     154µs ± 3%  -27.87%  (p=0.000 n=20+18)
ReadTreeSliF64/2-4           214µs ± 3%     156µs ± 4%  -27.31%  (p=0.000 n=20+20)
ReadTreeSliF64/4-4           214µs ± 3%     156µs ± 6%  -27.11%  (p=0.000 n=19+20)
ReadTreeSliF64/8-4           214µs ± 2%     155µs ± 5%  -27.50%  (p=0.000 n=18+20)
ReadTreeSliF64/16-4          214µs ± 3%     155µs ± 4%  -27.66%  (p=0.000 n=20+20)
ReadTreeSliF64/64-4          213µs ± 2%     155µs ± 3%  -27.14%  (p=0.000 …
```
> Groot reader perf

- groot/rtree/example_reader_test.go
- groot/rtree/formula.go
- groot/rtree/formula_test.go
- groot/rtree/reader.go
- groot/rtree/rfunc/gen-rfuncs.go
- groot/rtree/rfunc/rfunc.go
- groot/rtree/rfunc/rfunc_bool_gen.go
- groot/rtree/rfunc/rfunc_bool_gen_test.go
- groot/rtree/rfunc/rfunc_float32_gen.go
- groot/rtree/rfunc/rfunc_float32_gen_test.go
- groot/rtree/rfunc/rfunc_float64_gen.go
- groot/rtree/rfunc/rfunc_float64_gen_test.go
- groot/rtree/rfunc/rfunc_int32_gen.go
- groot/rtree/rfunc/rfunc_int32_gen_test.go
- groot/rtree/rfunc/rfunc_int64_gen.go
- groot/rtree/rfunc/rfunc_int64_gen_test.go
- groot/rtree/rfunc/rfunc_uint32_gen.go
- groot/rtree/rfunc/rfunc_uint32_gen_test.go
- groot/rtree/rfunc/rfunc_uint64_gen.go
- groot/rtree/rfunc/rfunc_uint64_gen_test.go
introducing the rfunc.Formula protocol brings this kind of performance
improvements:
```
$> benchstat ref.txt new-rfunc.txt
name                   old time/op    new time/op    delta
FormulaFunc/f0/Func-4     238ns ± 3%       4ns ± 1%   -98.20%  (p=0.000 n=20+16)
FormulaFunc/f1/Func-4     313ns ± 2%       5ns ± 5%   -98.39%  (p=0.000 n=20+19)
FormulaFunc/f2/Func-4     313ns ± 4%       5ns ± 3%   -98.31%  (p=0.000 n=20+20)
FormulaFunc/f3/Func-4     313ns ± 2%       5ns ± 4%   -98.32%  (p=0.000 n=18+20)
name                   old alloc/op   new alloc/op   delta
FormulaFunc/f0/Func-4     40.0B ± 0%      0.0B       -100.00%  (p=0.000 n=20+20)
FormulaFunc/f1/Func-4     48.0B ± 0%      0.0B       -100.00%  (p=0.000 n=20+20)
FormulaFunc/f2/Func-4     48.0B ± 0%      0.0B       -100.00%  (p=0.000 …
```
> groot/rtree{,/rfunc}: introduce rfunc.Formula protocol

- go.mod
- go.sum
go-mmap v0.2.0 exposes types that have an os.File.Stat()-like method.
this is useful for e.g. root-fuse (in go-hep.org/x/exp)
> groot/riofs: use go-mmap@v0.2.0

- xrootd/xrdio/parse.go
- xrootd/xrdio/parse_test.go
xrdio.Parse relied on net/url.Parse to parse URIs.
Unfortunately, URIs may not all be valid URLs.
Example:
root://example.org/dir/file.%c.txt
This CL re-implements xrdio.Parse with dedicated code.
Fixes go-hep/hep#774.
> xrootd/xrdio: implement correct URI parser

- .github/workflows/lint.yml
- groot/rtree/branch.go
Branches bound to empty slices for too long will overflow.
As an empty slice is... empty, nothing is written out, but the offsets slice keeps
growing.
Detect when the offsets slice will overflow and flush.
Fixes go-hep/hep#821.
> groot/rtree: flush branches bound to empty slices

- groot/rtree/branch.go
only keep one basket when writing.
this also reduces somewhat the on-disk size of TBranches.
> groot/rtree: reduce memory usage in tree-write

- groot/riofs/dir.go
- groot/riofs/file.go
- groot/riofs/key.go
- groot/rtree/basket.go
if a basket is created when a TFile is "small", but crosses over the
small/big file boundary, its "offsets" and "last" fields will be
inconsistent (by 8 bytes, ie: the number of bytes difference b/w
small/big TKeys).
This CL detects when such a case occurs and retro-actively adjusts these
fields.
Fixes go-hep/hep#826.
> groot/{riofs,rtree}: handle small/big file thresholds for long-running baskets

- groot/riofs/file_test.go
> groot/riofs: use SMHiggsToZZTo4L.root from ccxrootdgotest instead of eospublic.cern.ch

- groot/rhist/graph.go
- groot/rhist/rootio_test.go
> groot/rhist: correctly write out TGraph{,Asymm}{,Errors}

- cmd/root2arrow/main.go
- cmd/root2csv/main.go
- cmd/root2npy/main.go
This CL uses riofs.Dir to be able to retrieve possibly deeply nested
trees from a ROOT file's hierarchy.
> cmd/root2{arrow,csv,npy}: use riofs.Dir to retrieve trees

- cmd/root2npy/main.go
- cmd/root2npy/main_test.go
This CL modifies root2npy to process Trees column by column so only 1
numpy buffer is materialized in-memory.
```
$> benchstat ./ref.txt ./new.txt
name       old time/op    new time/op    delta
Process-8    2.48ms ± 1%    2.39ms ± 2%   -3.44%  (p=0.000 n=28+29)
name       old alloc/op   new alloc/op   delta
Process-8    3.50MB ± 1%    2.64MB ± 2%  -24.63%  (p=0.000 n=30+29)
name       old allocs/op  new allocs/op  delta
Process-8     3.41k ± 0%     3.28k ± 0%   -3.60%  (p=0.000 n=30+30)
```
> cmd/root2npy: improve memory usage

- groot/rcmd/dump.go
- groot/rcmd/dump_test.go
```
name    old time/op    new time/op    delta
Dump-8     5.02s ± 2%     3.98s ± 2%  -20.83%  (p=0.000 n=29+29)
name    old alloc/op   new alloc/op   delta
Dump-8    2.50GB ± 0%    2.40GB ± 0%   -3.82%  (p=0.000 n=29+30)
name    old allocs/op  new allocs/op  delta
Dump-8     38.8M ± 0%     29.3M ± 0%  -24.69%  (p=0.000 n=30+29)
```
> groot/rcmd: improve Dump tree performances

- xrootd/bench_test.go
- xrootd/file.go
This CL reduces the lock contention on xrootd.File operations.
```
$> benchstat ./ref.txt ./new.txt
name    old time/op    new time/op    delta
Read-8     67.2s ± 1%      5.4s ± 7%  -91.93%  (p=0.000 n=9+28)
name    old alloc/op   new alloc/op   delta
Read-8     343MB ± 0%     341MB ± 0%   -0.78%  (p=0.000 n=8+30)
name    old allocs/op  new allocs/op  delta
Read-8      277k ± 0%      288k ± 0%   +3.84%  (p=0.000 n=7+29)
```
and now:
```
$> time root-dump root://ccxrootdgotest.in2p3.fr:9001/tmp/rootio/testdata/SMHiggsToZZTo4L.root > /dev/null
real	0m7.279s
user	0m8.221s
sys	0m1.256s
```
compared to:
```
$> time root-dump https://cern.ch/binet/big-file.root > /dev/null
real	0m5.454s
user	0m6.156s
sys	0m0.228s
```
Updates #920.
> xrootd: improve read performances 10-fold

- groot/internal/httpio/httpio.go
- groot/internal/httpio/reader.go
- groot/internal/httpio/reader_test.go
- groot/internal/httpio/testdata/data.txt
- groot/riofs/plugin/http/http.go
- groot/riofs/plugin/http/preader.go
- groot/riofs/plugin/http/rcache.go
- groot/riofs/plugin/http/span.go
- groot/riofs/plugin/http/span_test.go
- groot/riofs/plugin/plugin_test.go
old: reading remote file after having downloaded to a local one
new: reading remote file w/ httpio + sync.Pool
```
name                    old time/op    new time/op    delta
DumpHTTP/delay-0s-8        279ms ± 1%     287ms ± 2%   +3.09%  (p=0.000 n=27+29)
DumpHTTP/delay-5ms-8       279ms ± 2%     288ms ± 2%   +3.06%  (p=0.000 n=29+29)
DumpHTTP/delay-10ms-8      281ms ± 3%     287ms ± 1%   +2.24%  (p=0.000 n=26+30)
DumpHTTP/delay-100ms-8     286ms ± 3%     288ms ± 1%   +0.45%  (p=0.032 n=25+29)
name                    old alloc/op   new alloc/op   delta
DumpHTTP/delay-0s-8        156MB ± 0%     159MB ± 0%   +1.93%  (p=0.000 n=29+30)
DumpHTTP/delay-5ms-8       156MB ± 0%     159MB ± 0%   +1.95%  (p=0.000 n=30+30)
DumpHTTP/delay-10ms-8      155MB ± 0%     159MB ± 0%   +1.95%  (p=0.000 …
```
> groot/internal/httpio: first import

- groot/riofs/walk.go
- groot/riofs/walk_example_test.go
- groot/riofs/walk_test.go
> groot/riofs: add generic Get[T] to retrieve ROOT objects

- sliceop/f64s/f64s.go
- sliceop/sliceop.go
- sliceop/sliceop_example_test.go
- sliceop/sliceop_test.go
Move and generalize code from sliceop/f64s into sliceop.
```
name                old time/op    new time/op    delta
Take/Len=2-8          2.69ns ± 1%    2.71ns ± 2%   +0.75%  (p=0.043 n=18+18)
Take/Len=4-8          3.18ns ± 1%    3.23ns ± 3%   +1.27%  (p=0.005 n=19+20)
Take/Len=8-8          3.83ns ± 1%    3.73ns ± 1%   -2.69%  (p=0.000 n=20+19)
Take/Len=128-8        44.1ns ± 4%    35.9ns ± 2%  -18.61%  (p=0.000 n=20+20)
Take/Len=1024-8        337ns ± 2%     280ns ± 6%  -16.73%  (p=0.000 n=19+20)
Take/Len=1048576-8    1.37ms ± 3%    1.31ms ± 5%   -3.97%  (p=0.000 n=19+20)
name                old alloc/op   new alloc/op   delta
Take/Len=2-8           0.00B          0.00B          ~     (all equal)
Take/Len=4-8           0.00B          0.00B          ~     (all equal)
Take/Len=8-8 …
```
> sliceop{,/f64s}: introduce generics sliceop

- groot/riofs/memfile.go
- groot/riofs/memfile_test.go
This CL export RMemFile, that provides a simple way to create in-memory
read-only ROOT files.
> groot/riofs: export in-memory read-only RMemFile ROOT file

- cmd/root2yoda/main.go
`log.Fatal` already returns exit code 1
found with [revive](https://github.com/mgechev/revive) rule `unreachable-code`
> removes unreacheable statement

- lhef/reader.go
Use `errors.New` instead of `fmt.Errorf` for constant messages.
> lhef: use errors.New instead of fmt.Errorf for constants

- lhef/reader.go
- lhef/reader_test.go
In the `lhef.Decoder`, allocate slices using sliced bigger chunks in order to reduce the number of allocations.
Example:
```
a := make([]int32, n)
b := make([]int32, n)
c := make([]int32, n)
```
is replaced with:
```
n32 := make([]int32, 3*n)
a := n32[:n:n]
b := n32[n : 2*n : 2*n]
b := n32[2*n:]
```
> lhef: reduce number of allocs in Decoder

- sliceop/f64s/f64s_test.go
- sliceop/sliceop.go
Use `errors.New` instead of `fmt.Errorf` when the message is a constant string.
> sliceop: use errors.New for constant errors

- fwk/dflow_test.go
- fwk/examples/fwk-ex-tuto-1/main.go
- fwk/examples/fwk-ex-tuto-2/main.go
- fwk/examples/fwk-ex-tuto-3/main.go
- fwk/examples/fwk-ex-tuto-6-write-data/main.go
- fwk/examples/fwk-ex-tuto-7-read-data/main.go
- fwk/fwk_test.go
- fwk/internal/fwktest/inputstream.go
- fwk/internal/fwktest/outputstream.go
- fwk/internal/fwktest/reducer.go
- fwk/internal/fwktest/svc1.go
- fwk/internal/fwktest/task1.go
- fwk/internal/fwktest/task2.go
- fwk/internal/fwktest/task3.go
- fwk/internal/fwktest/task4.go
- fwk/job/gocodec_test.go
- fwk/job/jsoncodec_test.go
- fwk/job/stmt_test.go
- fwk/svcbase.go
- fwk/taskbase.go
Fixes #941 .
1st commit:
```console
$ mkdir -p fwk/internal/fwktest
$ git mv fwk/testdata/*.go fwk/internal/fwktest
$ ( cd fwk/internal/fwktest; sed -i '' 's/package testdata/package fwktest/' *.go )
$ git add fwk/internal/fwktest
```
2nd commit:
```console
$ ( cd fwk; find . -name '*.go' -exec grep -Hq 'fwk/testdata' '{}' \; -print | xargs sed -i '' -e 's!fwk/testdata!fwk/internal/fwktest!' -e 's!testdata\.!fwktest.!' -e 's!some tools defined in testdata!some tools defined in fwktest!' )
$ git add fwk
```
> fwk: rename package testdata to internal/fwktest

- groot/rmeta/estltype_string.go
```console
go generate ./groot/rmeta
```
> groot/rmeta: regnerate stringer

- brio/cmd/brio-gen/main_test.go
In tests of brio-gen, when a failure occurs (generated output changes) the new version is kept on disk. This is the existing behaviour.
With this patch we remove the new version if there is no difference (test success). This allows to automatically remove those temporary files that are useful only for debugging a test failure.
> brio-gen: cleanup files produced by tests on test success

- groot/cmd/root-gen-type/.gitignore
- groot/cmd/root-gen-type/main.go
Use `go run` instead of requiring the binary to be already built.
> groot: fix go:generate portability for root-gen-type

- .github/workflows/ci.yml
> ci: add Go-1.19

- cmd/hepmc2root/main.go
> cmd/hepmc2root: improve documentation

- groot/riofs/file.go
groot was using flate.BestCompression (zlib and level=9) whereas ROOT/C++ is using flate.BestSpeed (zlib and level=1).
This CL configures groot to use flate.DefaultCompression (and zlib).
On "typical" payloads this amounts to:
```
$> time ./new-dbg -zip=zlib-1 -o groot-zlib-1.root
real 0m9.469s
user 0m8.644s
sys  0m0.872s
$> time ./new-dbg -zip=zlib-6 -o groot-zlib-6.root (proposed new default)
real 0m10.832s
user 0m10.422s
sys  0m0.972s
$> time ./new-dbg -zip=zlib-9 -o groot-zlib-9.root (go-hep@v0.35 default)
real 0m32.415s
user 0m32.550s
sys  0m1.086s
```
and for the disk sizes:
```
$> ll
87M Nov 12 15:19 groot-zlib-1.root
77M Nov 12 15:18 groot-zlib-6.root (proposed new default)
67M Nov 12 15:19 groot-zlib-9.root (go-hep@v0.35 default)
```
> groot/riofs: align default compression settings w/ ROOT

- groot/example_test.go
- groot/riofs/fileplugin.go
> groot/riofs: drop mmap-ing ROOT files by default, add file+mmap:// convenience protocol
